name: "gridai-run"

on:
  # push:
  pull_request:  
  schedule:
  # run at 13 min past the hour every day
  # MIN HOUR DOM MON DOW CMD
    - cron: 13 1,9,17 * * *

jobs:
  grid_optuna:
    runs-on: ubuntu-latest
    name: grid_optuna
    steps:
      - uses: actions/checkout@v2     
      - uses: robert-s-lee/gridai_action_login@main
        with:
          username: ${{ secrets.GRIDAI_USERNAME }} 
          key: ${{ secrets.GRIDAI_KEY }}       
      - id: run
        uses: robert-s-lee/gridai_action_run@main
        with:
          script_name: pytorch_lightning_simple.py 
      - run: |
          if [ "${{ steps.run.outputs.obj_status }}" != "succeeded" ]; then
            exit 1
          fi