name: "gridai lightning optuna"

on:
  push:
    paths:
      - action.yml
      - pytorch_lightning_simple.py
      - .github/workflows/gridai_run.yml 
  pull_request:  
    paths:
      - action.yml
      - pytorch_lightning_simple.py
      - .github/workflows/gridai_run.yml  
  schedule:
  # run at 13 min past the hour every day
  # MIN HOUR DOM MON DOW CMD
    - cron: 13 1,9,17 * * *

jobs:
  gridai-run:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v2

      - uses: gridai-actions/gridai-login@v0
        with:
          gridai-username: ${{ secrets.GRIDAI_USERNAME }} 
          gridai-key: ${{ secrets.GRIDAI_KEY }}

      - id: gridai-github
        run: |
          cd ${GITHUB_WORKSPACE}
          gridai.py create_run pytorch_lightning_simple.py --grid_args " --instance_type t2.medium  " --gha True
        shell: bash

      - id: gridai-localdir
        run: |
          cd ${GITHUB_WORKSPACE}
          gridai.py create_run pytorch_lightning_simple.py --grid_args " --localdir --instance_type t2.medium  " --gha True
        shell: bash        

      - id: gridai-localdir
        run: |
          cd ${GITHUB_WORKSPACE}
          gridai.py create_run pytorch_lightning_simple.py --grid_args " --localdir --instance_type t2.medium --dependency_file requirements.txt" --gha True
        shell: bash            